name: Full Cloud Deploy

on:
  push:
    branches:
      - main

jobs:
  # 1. Build e validação da aplicação
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build application
        run: |
          chmod +x mvnw # Concede permissão de execução ao Maven Wrapper
          ./mvnw clean package -DskipTests=true

      - name: Upload application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw sonar:sonar \
          -Dsonar.projectKey=Lucas-lds_Grupo-34-8SOAT-FIAP \
          -Dsonar.organization=lucas-lds \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

  # 2. Provisionar infraestrutura com Terraform (sem destroy)
  provision-infrastructure:
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=tfplan
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply (Conditional)
        if: steps.terraform-plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Check Outputs in Terraform
        run: |
          terraform output gateway_url
          terraform output cognito_user_pool_id
        working-directory: terraform/
      
      - name: Export Infra Variables
        id: export-vars
        run: |
          GATEWAY_URL=$(terraform output -raw gateway_url)
          COGNITO_USER_POOL_ID=$(terraform output -raw cognito_user_pool_id)
          echo "GATEWAY_URL=$GATEWAY_URL"
          echo "COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID"
          echo "GATEWAY_URL=$GATEWAY_URL" >> $GITHUB_ENV
          echo "COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID" >> $GITHUB_ENV
        working-directory: terraform/

  # 3. Configuração dinâmica do backend e deploy no Kubernetes
  configure-backend:
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download application artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Inject Configurations into Deployment
        run: |
          sed -i "s|{GATEWAY_URL}|$GATEWAY_URL|g" kubernetes/deployment.yaml
          sed -i "s/{COGNITO_USER_POOL_ID}/$COGNITO_USER_POOL_ID/g" kubernetes/deployment.yaml

      - name: Deploy application to Kubernetes
        run: |
          kubectl apply -f kubernetes/
          kubectl rollout status deployment my-app

  # 4. Deploy da função Lambda
  deploy-lambda:
    runs-on: ubuntu-latest
    needs: provision-infrastructure
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda
        run: |
          zip function.zip lambda/lambda_function.py
          aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_NAME }} --zip-file fileb://function.zip
